### ISSUE TITLE
Too many parallel requests with the same access key

### ISSUE THREAD

**Issue by VikomiC** [aurora-is-near/aurora-relayer#226]
Got this error.

[ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32603,"message":"Internal Error - Error: nonce retries exceeded for transaction.

This usually means there are too many parallel requests with the same access key.. Please report a bug at <https://github.com/aurora-is-near/aurora-relayer/issues>","data":{"host":"r003.westcoast.us.testnet.internal.aurora.dev","cf-ray":"6e7e34893629b49c-IAD"}}}}'

**Comment by mfornet** [comment]
Public RPC currently supports 200tx per second, we have 200 NEAR keys and we rotate them to avoid nonce issues. However, testnet public RPC is under heavy load lately (>>200tx/s) so these keys are not enough.

We are working on spam prevention that should mitigate the heavy load on testnet.

I'm closing this issue, since we are aware of limitations of public RPC. In general a more reliable (but complex) solution would be to [deploy your own endpoint](https://github.com/aurora-is-near/partner-relayer-deploy).
